### ISSUE TITLE
env.reset() bug?

### ISSUE THREAD

**Issue by emigmo** [GOAL-Robots/REALCompetitionStartingKit#10]
![image](https://user-images.githubusercontent.com/10398640/61444384-e0db8600-a97d-11e9-9d03-083f0ee786d1.png)
running the demo file but the reset() report error.

**Comment by emilio-cartoni** [comment]
Dear @emigmo,
this is probably due to having an older version of pybullet.
Try to update your pybullet package.

**Comment by emigmo** [comment]
Done, thank you
