### ISSUE TITLE
Add repo link to AICrowd page?

### ISSUE THREAD

**Issue by colllin** [GOAL-Robots/REALCompetitionStartingKit#5]
Hi!  I’m really excited about this competition!

I was wondering when the “beta” was going to start, kept checking the official AICrowd page for the comp, and finally decided to google for it and ended up here.

Is this the official repo and env for the competition?  How would you feel about adding a link to it in the competition description so more people can get in on the beta and start preparing their development environments?

**Comment by emilio-cartoni** [comment]
Hi Collin and welcome!
Yes, you have landed on the right page, this will be the official repo and environment for the competition.
I agree with your suggestion and I have added the link the the competition description, so that people can start to have a look at it.
