### ISSUE TITLE
About Goal Retina Output 

### ISSUE THREAD

**Issue by KelvinCPChiu** [GOAL-Robots/REALCompetitionStartingKit#9]
I am trying to write sampling function on top of the demo.

env = gym.make('REALComp-v0')
observation, reward, done, _ = env.step(action)

either one of them will result a random noisy map only.

obs = observation[env.robot.ObsSpaces.GOAL]
goal = env.goal.retina

while the obs = observation[env.robot.ObsSpaces.RETINA] outputs properly.

However, RETINA and Goal should get the same gym.spaces.Box according to self.observation_space defined in Kuka/self.robot.

Can you explain more in detail how to set the goal or sampling the goal ? Also, what is the initial position and final position representing in the Goal function ? 

class Goal:
    def __init__(self, initial_state=[0, 0, 0], 
            final_state=[0, 0, 0], retina=None):
        self.initial_state = initial_state
        self.final_state = final_state
        self.retina = retina

I could not see how this goal function will result any rendering or modification in the environment.
It would be great if you could explain how should we define the set_goal().

**Comment by emilio-cartoni** [comment]
Dear KelvinCPChlu,

if you receive a random noise on 'goal' observation, please ensure that you have the latest version of the repository.
Earlier versions of the repository had "random noise" as a placeholder for goals.
Current version should give you as 'goal' normal images with objects placed in various positions of the table.

Notice that the file goals_dataset.npy (which is where the goals come from) is not finalized yet, so you will probably not see objects on the shelf (goal type "2.5D") or objects on top of each other (which can happen in goal type "3D").

As you can see in demo.py, the environment as a set_goal() function.
Before the first call to that function, there is no observable goal (the 'goal' observation should be a black image). This corresponds to the Intrinsic Phase of the simulation.

Later, in the Extrinsic Phase, each time the set_goal function is called, a new goal is set and displayed in the 'goal' observation and the objects are moved to the positions specified in the "initial_state" variable.
The final_state is instead used for the final extrinsic score and it contains the positions of the objects as you see them in the goal image.

I am not sure if I understood your last part (i.e. "how should we define the set_goal()") so let me know if you need further info.

**Comment by KelvinCPChiu** [comment]
Thanks. Your have answered my questions.
